history.mongo.host: localhost
history.mongo.database: historyDev
history.hostname: localhost

history.api.security:
  accessKeys:
    - key: 'test_read_key'
      auth: 'test_read_auth'
      roles:
        - 'read'
    - key: 'test_write_key'
      auth: 'test_write_auth'
      roles:
        - 'write'